<header class='navbar navbar-default navbar-static-top'>
  <nav class='container' role='navigation'>
    <div class='navbar-header'>
      <?php echo $this->tag->linkTo(array("", '<i class="fa fa-paw" aria-hidden="true"></i> PHALCON-ZOO', "class" => "navbar-brand title-green"));?>
    </div>

    <ul class='nav navbar-nav navbar-right collapse navbar-collapse'>
      <li><?php echo $this->tag->linkTo(array("signup", "Sign Up", "class" => "title-green"));?></li>
    </ul>
  </nav>
</header>
