<header class='navbar navbar-default navbar-static-top'>
  <nav class='container' role='navigation'>
    <div class='navbar-header'>
      <?php echo $this->tag->linkTo(array("", "Home", "class" => "navbar-brand"));?>
    </div>

    <ul class='nav navbar-nav navbar-right collapse navbar-collapse'>
      <li><?php echo $this->tag->linkTo("signup", "Sign Up Here!");?></li>
    </ul>
  </nav>
</header>
