<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>phalcon-zoo</title>
    <link rel="icon" type="image/png" href="img/falcon-icon.png" />
    <link rel="stylesheet" href="./bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="./bower_components/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="./css/style.css" />
  </head>
  <body>
    <?php require (__DIR__ . '/../navbar/navbar.phtml') ?>

    <div class="col-md-1 menu">
      <?php require (__DIR__ . '/../menu/menu.phtml') ?>
    </div>

		<div class="col-md-10">
      <div class ="row>">
				<div class="col-md-6">
					<h2>Sign using this form</h2>

					<?php echo $this->tag->form('signup/register') ?>

						<div class="form-group">
							<label for="name">Name</label>
							<?php echo $this->tag->textField(array("name", "class" => "form-control")) ?>
						</div>

						<div class="form-group">
							<label for="name">E-Mail</label>
							<?php echo $this->tag->textField(array("email", "class" => "form-control")) ?>
						</div>

							<?php echo $this->tag->submitButton(array("Register", "class" => "btn btn-submit")) ?>

					</form>
				</div>
      </div>
    </div>

    <script src="./bower_components/jquery/dist/jquery.min.js"></script>
    <script src="./bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

  </body>
</html>
