<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>zoo-phalcon</title>
    <link rel="icon" type="image/png" href="img/falcon-icon.png" />
    <link rel="stylesheet" href="./bower_components/bootstrap/dist/css/bootstrap.css" />
  </head>
  <body>
    <?php require (__DIR__ . '/../navbar/navbar.phtml') ?>

    <div class="col-md-12">
      <div class ="row>">
				<h2>Sign using this form</h2>

				<?php echo $this->tag->form('signup/register') ?>

					<p>
						<label for="name">Name</label>
						<?php echo $this->tag->textField("name") ?>
					</p>

					<p>
						<label for="name">E-Mail</label>
						<?php echo $this->tag->textField("email") ?>
					</p>

					<p>
						<?php echo $this->tag->submitButton("Register") ?>
					</p>

				</form>
      </div>
    </div>
  </body>
</html>
