<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>phalcon-zoo</title>
    <link rel="icon" type="image/png" href="img/falcon-icon.png" />
    <link rel="stylesheet" href="./bower_components/bootstrap/dist/css/bootstrap.css" />
  </head>
  <body>
    <?php require (__DIR__ . '/../navbar/navbar.phtml') ?>

    <div class="col-md-10 col-md-offset-1">
      <div class ="row>">
        <?php echo "<h1>Welcome to the phalcon-zoo !</h1>"; ?>
      </div>
    </div>
  </body>
</html>
